version: "3"
services:
  authentication:
    build: ./authentication
    environment:
      - JWTSECRET=ITSSOSECRET
      - PORT=6010
    volumes:
      - ./authentication:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 6010:6010
  hello:
    build: ./hello
    environment:
      - JWTSECRET=ITSSOSECRET
      - PORT=6020
    volumes:
      - ./hello:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 6020:6020