version: "3"
services:
  authentication:
    build: ./authentication
    volumes:
      - ./authentication:/usr/src/app
    ports:
      - 6010:6010
  hello:
    build: ./hello
    volumes:
      - ./hello:/usr/src/app
    ports:
      - 6020:6020